# Generated by Django 4.2.11 on 2026-06-26 20:49

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('location_lat', models.FloatField(help_text='Shop latitude')),
                ('location_lng', models.FloatField(help_text='Shop longitude')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('business_hours', models.JSONField(blank=True, default=dict, help_text='Business hours in JSON format: {mon: {open: 09:00, close: 18:00}, ...}')),
                ('rating_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('total_ratings', models.IntegerField(default=0)),
                ('subscription_tier', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], default='basic', max_length=10)),
                ('subscription_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('images', models.JSONField(blank=True, default=list, help_text='Array of image URLs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'shops',
            },
        ),
    ]
