# Generated by Django 4.2.11 on 2026-06-26 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'user_type': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['owner'], name='shops_owner_i_55f30a_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['subscription_tier'], name='shops_subscri_4686ac_idx'),
        ),
        migrations.AddIndex(
            model_name='shop',
            index=models.Index(fields=['is_active'], name='shops_is_acti_1c534c_idx'),
        ),
    ]
