# Generated by Django 4.2.11 on 2026-06-26 20:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaadakaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name or SVG reference', max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='vaadaka.vaadakacategory')),
            ],
            options={
                'verbose_name_plural': 'Vaadaka Categories',
                'db_table': 'vaadaka_categories',
            },
        ),
        migrations.CreateModel(
            name='Vaadaka',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair')], default='good', max_length=10)),
                ('images', models.JSONField(blank=True, default=list, help_text='Array of image URLs')),
                ('quantity_available', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_total', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('price_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('minimum_rental_duration', models.IntegerField(default=1, help_text='Minimum rental duration in hours')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Vaadaka specifications in JSON format')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaadakas', to='vaadaka.vaadakacategory')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaadakas', to='shops.shop')),
            ],
            options={
                'db_table': 'vaadakas',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shops.shop')),
                ('vaadaka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vaadaka.vaadaka')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.AddIndex(
            model_name='vaadaka',
            index=models.Index(fields=['shop'], name='vaadakas_shop_id_8ddde3_idx'),
        ),
        migrations.AddIndex(
            model_name='vaadaka',
            index=models.Index(fields=['category'], name='vaadakas_categor_1bbf92_idx'),
        ),
        migrations.AddIndex(
            model_name='vaadaka',
            index=models.Index(fields=['is_available'], name='vaadakas_is_avai_7d5326_idx'),
        ),
        migrations.AddIndex(
            model_name='vaadaka',
            index=models.Index(fields=['-created_at'], name='vaadakas_created_3c83fd_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['shop'], name='reviews_shop_id_2a946a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['vaadaka'], name='reviews_vaadaka__2c28d2_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='reviews_created_6c5dce_idx'),
        ),
    ]
