# Generated by Django 4.2.11 on 2026-06-26 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsubscription',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='shops.shop'),
        ),
        migrations.AddIndex(
            model_name='shopsubscription',
            index=models.Index(fields=['shop'], name='shop_subscr_shop_id_935de2_idx'),
        ),
        migrations.AddIndex(
            model_name='shopsubscription',
            index=models.Index(fields=['status'], name='shop_subscr_status_34fdb2_idx'),
        ),
        migrations.AddIndex(
            model_name='shopsubscription',
            index=models.Index(fields=['expires_at'], name='shop_subscr_expires_861dc6_idx'),
        ),
    ]
